branches:
  only:
    - master
sudo: required
services:
  - docker
script:
  - docker build -t caronte .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag caronte $DOCKER_USER/caronte:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/caronte:$TRAVIS_BUILD_NUMBER
  - docker tag caronte $DOCKER_USER/caronte:latest
  - docker push $DOCKER_USER/caronte:latest
